// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pe.com.cybersec.partition.domain;

import org.springframework.beans.factory.annotation.Configurable;
import pe.com.cybersec.partition.domain.Catalogo;

privileged aspect Catalogo_Roo_Configurable {
    
    declare @type: Catalogo: @Configurable;
    
}
