// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pe.com.cybersec.partition.jsf.converter;

import org.springframework.beans.factory.annotation.Configurable;
import pe.com.cybersec.partition.jsf.converter.CatalogoConverter;

privileged aspect CatalogoConverter_Roo_Configurable {
    
    declare @type: CatalogoConverter: @Configurable;
    
}
