// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pe.com.cybersec.partition.jsf.converter;

import org.springframework.beans.factory.annotation.Configurable;
import pe.com.cybersec.partition.jsf.converter.DetalleCatalogoConverter;

privileged aspect DetalleCatalogoConverter_Roo_Configurable {
    
    declare @type: DetalleCatalogoConverter: @Configurable;
    
}
