// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pe.com.cybersec.partition.jsf;

import java.io.Serializable;
import pe.com.cybersec.partition.jsf.CatalogoBean;

privileged aspect CatalogoBean_Roo_Serializable {
    
    declare parents: CatalogoBean implements Serializable;
    
    private static final long CatalogoBean.serialVersionUID = 1L;
    
}
