// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pe.com.cybersec.partition.jsf;

import org.springframework.beans.factory.annotation.Configurable;
import pe.com.cybersec.partition.jsf.DetalleCatalogoBean;

privileged aspect DetalleCatalogoBean_Roo_Configurable {
    
    declare @type: DetalleCatalogoBean: @Configurable;
    
}
